#!/bin/bash  
#SBATCH --job-name=YOLOV10_val_yolov11
#SBATCH --nodes=1  
#SBATCH --ntasks=1  
#SBATCH --mem=100G  
#SBATCH --partition=gpu  
#SBATCH --time=24:00:00  
#SBATCH --gres=gpu:V100-SXM2-32GB:2
#SBATCH --mail-type=BEGIN,FAIL,END,REQUEUE
#SBATCH --mail-user=jztk7@mst.edu
#SBATCH --output=Mill_Output/Mill-%j.out
#SBATCH --error=Mill_Output/Mill-%j.err

echo "=================== Script content: $0 ====================="
cat "$0"
echo "============================================================"

# 1) load anaconda
module load anaconda

# 2) let shell support conda activate
eval "$(conda shell.bash hook)"

# 3) activate env 
conda activate yolo

# 4) Debug
echo "Environment activated"
which python
python --version

# 5) GPU name
export CUDA_VISIBLE_DEVICES=0,1

# 6) test if CUDA is good
nvidia-smi
python -c "import torch; 
print(torch.version.cuda)
print('CUDA available:', torch.cuda.is_available()); 
print('CUDA device count:', torch.cuda.device_count());
print('CUDA current device:', torch.cuda.current_device());
print('CUDA device name:', torch.cuda.get_device_name(torch.cuda.current_device()))"

# 7) val
yolo detect val data="ultralytics/cfg/datasets/FLIR_v2_RGB_thermal.yaml" model="yolov8n.pt" batch=128 device=0,1

